DROP TABLE INBODY;

CREATE TABLE INBODY(
    IN_ID INT(8) AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    IN_HEIGHT FLOAT NOT NULL,
    IN_WEIGHT FLOAT NOT NULL,
    IN_SCORE FLOAT,
    IN_FAT FLOAT,
    IN_MUSCLE FLOAT,
    IN_C_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
    ON DELETE CASCADE
);

COMMIT;

INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.7, 73.4, 64, 20.7, 23.5);
INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.7, 74.2, 61, 21.3, 24.5);
INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.7, 72.3, 65, 19.9, 22.1);
INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.7, 71.0, 66, 19.6, 22.3);
INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.3, 72.0, 63, 21.2, 22.0);
INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.3, 71.4, null, 21.5, 21.7);

COMMIT;
