DROP TABLE INBODY;

CREATE TABLE INBODY(
    IN_ID INT(8) AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    IN_HEIGHT INT(3) NOT NULL,
    IN_WEIGHT INT(3) NOT NULL,
    IN_SCORE INT(3),
    IN_FAT INT(3),
    IN_MUSCLE INT(3),
    IN_C_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
    ON DELETE CASCADE
);

COMMIT;

INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.7, 73.4, 64, 20.7, 23.5);
INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.7, 74.2, 61, 21.3, 24.5);
INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.7, 72.3, 65, 19.9, 22.1);
INSERT INTO INBODY(USER_ID, IN_HEIGHT, IN_WEIGHT, IN_SCORE, IN_FAT, IN_MUSCLE)
VALUES('test', 163.7, 71.0, 66, 19.6, 22.3);

COMMIT;