DROP TABLE LOGIN_LOG;

CREATE TABLE LOGIN_LOG(
    L_ID INT(8) AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    L_IP VARCHAR(255) NOT NULL,
    L_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
    ON DELETE CASCADE
);

COMMIT;

SELECT DATE(L_DT) AS DATE, COUNT(*) AS AMOUNT FROM LOGIN_LOG
WHERE DATE(L_DT) BETWEEN '2023-07-28' AND '2023-07-28'
GROUP BY DATE(L_DT)
ORDER BY DATE(L_DT) DESC;

SELECT USER_ID, COUNT(*) AS AMOUNT FROM LOGIN_LOG
WHERE DATE(L_DT) BETWEEN '2023-07-20' AND '2023-07-27'
GROUP BY USER_ID;
ORDER BY AMOUNT DESC;


-- 조금 보류 해야할 듯;;
-- 쿼리는 의도한대로 나왔는데, 차트를 어떻게 그려야할지가 감이 안잡힘
SELECT L.L_IP, DATE(L_DT) AS DATE, COUNT(*) AS AMOUNT, U.USER_ROLE, U.USER_GENDER
FROM LOGIN_LOG L, USER_INFO U
WHERE
    L.USER_ID = U.USER_ID
    AND
    DATE(L.L_DT) BETWEEN '2023-07-15' AND '2023-07-28'
GROUP BY DATE(L_DT), U.USER_ROLE
ORDER BY DATE(L_DT) DESC;

SELECT COUNT(*) AS AMOUNT, DATE(USER_C_DT) AS DATE FROM USER_INFO
WHERE DATE(USER_C_DT) BETWEEN '2023-07-22' AND '2023-07-28'
GROUP BY DATE(USER_C_DT)
ORDER BY DATE(USER_C_DT);

SELECT COUNT(*) AS AMOUNT, USER_ROLE FROM USER_INFO
GROUP BY USER_ROLE
ORDER BY DATE(USER_C_DT);