CREATE TABLE LOGIN_LOG(
    L_ID INT(8) AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    L_IP VARCHAR(255) NOT NULL,
    L_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
    ON DELETE CASCADE
);

COMMIT;

SELECT DATE(L_DT) AS DATE, COUNT(*) AS AMOUNT FROM LOGIN_LOG
WHERE DATE(L_DT) BETWEEN '2023-07-23' AND '2023-07-27'
GROUP BY DATE(L_DT)
ORDER BY DATE(L_DT) DESC;

SELECT USER_ID, COUNT(*) AS AMOUNT FROM LOGIN_LOG
WHERE DATE(L_DT) BETWEEN '2023-07-20' AND '2023-07-27'
GROUP BY USER_ID;
ORDER BY AMOUNT DESC;