DROP TABLE PAYMENT;

CREATE TABLE PAYMENT(
    P_IDX INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    TP_IDX INT(8) NOT NULL,
    TID VARCHAR(20) NOT NULL,
    P_STATUS INT(1) NOT NULL DEFAULT 0,
    P_A_DT DATE NOT NULL,
    P_PT_PERIOD INT(2) NOT NULL,
    P_M_DT DATE,
    P_PT_CNT INT(3) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TP_IDX) REFERENCES PRODUCT(TP_IDX) ON DELETE CASCADE
);

COMMIT;

# 못쓰는 PT권 (TID변경 필요)
INSERT INTO PAYMENT (USER_ID, TP_IDX, TID, P_STATUS, P_A_DT, P_PT_PERIOD, P_PT_CNT)
VALUES ('test96', 2, 'TXXXXXXXX', 0, '2023/06/13', 1, 2);

# 정상적인 PT권
INSERT INTO PAYMENT (USER_ID, TP_IDX, TID, P_STATUS, P_A_DT, P_PT_PERIOD, P_PT_CNT)
VALUES ('test96', 2, 'T1XXXXXXX', 0, '2023/07/18', 90, 22);
INSERT INTO PAYMENT (USER_ID, TP_IDX, TID, P_STATUS, P_A_DT, P_PT_PERIOD, P_PT_CNT)
VALUES ('test96', 3, 'T2XXXXXXX', 0, '2023/06/20', 90, 36);
INSERT INTO PAYMENT (USER_ID, TP_IDX, TID, P_STATUS, P_A_DT, P_PT_PERIOD, P_PT_CNT)
VALUES ('test96', 4, 'T3XXXXXXX', 0, '2023/07/23', 90, 30);

# 환불
INSERT INTO PAYMENT (USER_ID, TP_IDX, TID, P_STATUS, P_A_DT, P_PT_PERIOD, P_M_DT, P_PT_CNT)
VALUES ('test96', 5, 'T4XXXXXXX', 1, '2023/07/20', 90, '2023/07/21', 30);