DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
    TP_IDX INT(8) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    TP_TITLE VARCHAR(100) NOT NULL,
    TP_PRICE INT(7) NOT NULL,
    TP_TYPE INT(1) NOT NULL,
    TP_PERIOD INT(2) NOT NULL,
    TP_TIMES INT(3) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE
);

COMMIT;

INSERT INTO PRODUCT
VALUES(NULL, 'wkdgyfla97', '바디프로필 3개월 패키지(개인)', 600000, 0, 90, 24);
INSERT INTO PRODUCT
VALUES(NULL, 'hye8997', '생활근력 만들기(단체)', 400000, 0, 60, 24);

COMMIT;