CREATE TABLE QNA(
    Q_IDX INT(8) AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    PQ_IDX INT(8),
    Q_CONTENT VARCHAR(1000) NOT NULL,
    Q_C_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
);

INSERT INTO QNA(USER_ID, Q_CONTENT)
VALUES("test2", "first QNA is QNA");

INSERT INTO QNA(USER_ID, PQ_IDX, Q_CONTENT)
VALUES("test", 1, "first comment for first QNA");