DROP TABLE RESERVATION;

CREATE TABLE RESERVATION(
    R_IDX INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    T_IDX INT(8) NOT NULL,
    USER_ID VARCHAR(30) NOT NULL,
    R_C_DT DATE NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (T_IDX) REFERENCES TIMETABLE(T_IDX) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE
);

COMMIT;

INSERT INTO RESERVATION
VALUES(NULL, '2', 'wkdgyfla97', current_date);
INSERT INTO RESERVATION
VALUES(NULL, '1', 'ujeong', current_date);
