DROP TABLE REVIEW;
DROP TABLE REVIEW_IMAGE;

CREATE TABLE REVIEW(
    R_IDX INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    UT_IDX INT(8) NOT NULL,
    R_CONTENT VARCHAR(1000) NOT NULL,
    R_STAR INT(1) NOT NULL DEFAULT '3',
    R_C_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    R_M_DT TIMESTAMP,
    FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY(UT_IDX) REFERENCES TRAINER_DETAILS(UT_IDX) ON DELETE CASCADE
);
ALTER TABLE 'REVIEW' AUTO_INCREMENT = 0;

CREATE TABLE REVIEW_IMAGE(
    RI_IDX INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    R_IDX INT(8) NOT NULL,
    RI_PATH VARCHAR(1000) NOT NULL,
    FOREIGN KEY (R_IDX) REFERENCES REVIEW(R_IDX) ON DELETE CASCADE
);
ALTER TABLE 'REVIEW_IMAGE' AUTO_INCREMENT = 0;

COMMIT;

INSERT INTO REVIEW
VALUES();
INSERT INTO REVIEW
VALUES();

INSERT INTO REVIEW_IMAGE
VALUES();
INSERT INTO REVIEW_IMAGE
VALUES();
