DROP TABLE TIMETABLE;

CREATE TABLE TIMETABLE(
    T_IDX INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UT_IDX INT(8) NOT NULL,
    T_DATE DATE NOT NULL,
    T_START_T TIME NOT NULL,
    T_END_T TIME NOT NULL,
    T_PEOPLE INT(3) NOT NULL DEFAULT '1',
    T_TYPE INT(1) NOT NULL DEFAULT '0',
    FOREIGN KEY (UT_IDX) REFERENCES TRAINER_DETAILS(UT_IDX) ON DELETE CASCADE
);

COMMIT;

INSERT INTO TIMETABLE
VALUES(NULL, '1', '2023/05/23', '09:00', '10:00', '3', '0');
INSERT INTO TIMETABLE
VALUES(NULL, '1', '2023/05/25', '09:00', '10:00', '1', '1');
